// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectedDeviceType } from "./ConnectedDeviceType";
import type { DeviceDetails } from "./DeviceDetails";

export interface ConnectedDevice { id: string, vendor_id: number, product_id: number, description: string | null, serial_number: string | null, device_type: ConnectedDeviceType | null, device_details: DeviceDetails | null, }