// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectedDeviceType } from "./ConnectedDeviceType";
import type { DeviceDetails } from "./DeviceDetails";
import type { Release } from "./Release";

export interface ConnectedDevice { id: string, releases: Array<Release> | null, vendor_id: number, product_id: number, device_type: ConnectedDeviceType, description: string | null, serial_number: string | null, device_details: DeviceDetails | null, }