// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asset } from "./Asset";

export interface Release { url: string, html_url: string, assets_url: string, upload_url: string, tarball_url: string | null, zipball_url: string | null, discussion_url: string | null, id: bigint, node_id: string, tag_name: string, target_commitish: string, name: string | null, body: string | null, draft: boolean, prerelease: boolean, created_at: string, published_at: string | null, assets: Array<Asset>, }