name: Release
on:
  push:
    branches:
      - main
jobs:
  # Job that allows the creation of the release
  release_please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_id: ${{ steps.release.outputs.id }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

  # Job that builds the executables
  build_tauri:
    name: "Build and upload release binaries"
    needs: release_please
    if: ${{ needs.release_please.outputs.release_created }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          #- platform: macos-latest
          #  target: aarch64-apple-darwin
          - platform: macos-latest
            target: x86_64-apple-darwin
          #- platform: ubuntu-latest
          #  target: aarch64-unknown-linux-gnu
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          #- platform: windows-latest
          #  target: aarch64-pc-windows-msvc
          - platform: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "ahoy"
          shared-key: "tauri-release"
          workspaces: src-tauri

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: make dist dir
        run: mkdir dist

      - name: install app dependencies and build it
        run: npm install --legacy-peer-deps && npm run build

      - name: windows - build driver installer
        if: matrix.platform == 'windows-latest'
        run: re-pack-files
        shell: cmd
        working-directory: src-tauri\wix\drivers

      - name: Set providerShortName in tauri.conf.json
        if: matrix.platform == 'macos-latest'
        uses: jossef/action-set-json-field@v2.1
        with:
          file: src-tauri/tauri.conf.json
          field: tauri.bundle.macOS.providerShortName
          value: ${{ secrets.APPLE_TEAM_ID }}

      - name: Set signingIdentity in tauri.conf.json
        if: matrix.platform == 'macos-latest'
        uses: jossef/action-set-json-field@v2.1
        with:
          file: src-tauri/tauri.conf.json
          field: tauri.bundle.macOS.signingIdentity
          value: ${{ secrets.APPLE_SIGNING_IDENTITY }}

      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
        with:
          args: --target ${{ matrix.target }}
          releaseId: ${{ needs.release_please.outputs.release_id }}
